# Template for ibutsu stage server
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ibutsu-postgres-stage-template
# ===============================================
# PostgreSQL
# ===============================================
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
      template: postgresql-persistent-template
    name: postgresql
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      deploymentConfig: postgresql
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentConfig: postgresql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: postgresql
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: postgresql
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: postgresql
          image: postgresql:12
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /usr/libexec/check-container
              - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 10
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:12
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
# -----------------------------------------------
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: postgresql
    namespace: ${NAMESPACE}
  spec:
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      deploymentConfig: postgresql
# -----------------------------------------------
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: postgresql
    namespace: ${NAMESPACE}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${POSTGRESQL_STORAGE}
# -----------------------------------------------
- kind: Secret
  apiVersion: v1
  metadata:
    name: postgresql
    namespace: ${NAMESPACE}
  type: opaque
  stringData:
    database-name: ${POSTGRESQL_DATABASE}
    database-password: ${POSTGRESQL_PASSWORD}
    database-user: ${POSTGRESQL_USER}
# ===============================================
# Parameters
# ===============================================
parameters:
- name: POSTGRESQL_USER
  displayName: PostgreSQL User
  description: The username for authentication in PostgreSQL
  generate: expression
  from: 'user[\a\d]{4}'
- name: POSTGRESQL_PASSWORD
  displayName: PostgreSQL Password
  description: The password for the PostgreSQL user
  generate: expression
  from: '[\w]{16}'
- name: POSTGRESQL_DATABASE
  displayName: PostgreSQL Database
  description: The name of the database to use in PostgreSQL
  value: ibutsu
- name: POSTGRESQL_STORAGE
  displayName: PostgreSQL Storage
  description: The amount of storage space for the database to use
  value: 40Gi
- name: APP_NAME
  displayName: App Name
  description: The name of the application
  value: ibutsu-server
- name: NAMESPACE
  displayName: Namespace
  description: The namespace for all of the images, applications, etc.
  value: iqe-stage-ibutsu-server
