codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 100%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: success
    patch:
      default:
        informational: true
        target: auto
        threshold: 100%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: success

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "backend/ibutsu_server/test/"
  - "backend/tests/"
  - "backend/ibutsu_server/migrations/"
  - "frontend/src/**/*.test.js"
  - "frontend/cypress/"
  - "docs/"
  - "*.md"
  - "scripts/"
