ignore:
    - .git
    - venv
    - .venv
    - .ibutsu-env
    - env
    - .env
    - .tox
    - frontend/node_modules
    - vendor
    - .postgres-data
    - .redis-data
    - .ruff_cache
    - .jwtsecret
    - .pytest_cache
    - .mypy_cache

rule_settings:
  enable: [default]
  disable: []
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: '3.9'

rules: []

metrics:
  quality_threshold: 25.0

github:
  labels: []
  ignore_labels:
    - sourcery-ignore
  request_review: author
  sourcery_branch: sourcery/{base_branch}

clone_detection:
  min_lines: 4
  min_duplicates: 3
  identical_clones_only: false

proxy:
  no_ssl_verify: false
