services:
  postgres:
    environment:
      POSTGRES_USER: ibutsu
      POSTGRES_PASSWORD: ibutsu
      POSTGRES_DB: ibutsu
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ibutsu" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest

  backend:
    hostname: backend
    environment:
      APP_CONFIG: config.py
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: ibutsu
      POSTGRESQL_USER: ibutsu
      POSTGRESQL_PASSWORD: ibutsu
      IBUTSU_SUPERADMIN_EMAIL: admin@example.com
      IBUTSU_SUPERADMIN_PASSWORD: admin12345
      IBUTSU_SUPERADMIN_NAME: Administrator
      JWT_SECRET: jwtsecret
      CELERY_BROKER_URL: 'redis://redis'
      CELERY_RESULT_BACKEND: 'redis://redis'
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.backend
    image: ibutsu/backend
    command: /bin/bash -c 'python -m ibutsu_server --host 0.0.0.0'
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --output /dev/null --silent --head --fail http://backend:8080/api/health
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    environment:
      APP_SCRIPT: celery_worker.sh
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: ibutsu
      POSTGRESQL_USER: ibutsu
      POSTGRESQL_PASSWORD: ibutsu
      IBUTSU_SUPERADMIN_EMAIL: admin@example.com
      IBUTSU_SUPERADMIN_PASSWORD: admin12345
      IBUTSU_SUPERADMIN_NAME: Administrator
      CELERY_BROKER_URL: 'redis://redis'
      CELERY_RESULT_BACKEND: 'redis://redis'
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.worker
    image: ibutsu/worker
    depends_on:
      backend:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  api-tests:
    environment:
      IBUTSU_SUPERADMIN_EMAIL: admin@example.com
      IBUTSU_SUPERADMIN_PASSWORD: admin12345
      IBUTSU_SUPERADMIN_NAME: Administrator
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.fuzz_testing
    image: ibutsu/fuzz_testing
    depends_on:
      backend:
        condition: service_healthy
