import { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

// Assisted by watsonx Code Assistant
// Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.

export const useTabHook = (validTabIndicies=[], defaultTab) => {

  const location = useLocation();
  const navigate = useNavigate();
  const currentHash = location.hash.slice(1);
  const activeTab = validTabIndicies.includes(currentHash) ? currentHash : defaultTab;

  useEffect(() => {
    // catch a bad tab index and use the default
    if (!validTabIndicies.includes(location.hash.slice(1))) {navigate(`#${defaultTab}`);}
  }, [defaultTab, location.hash, navigate, validTabIndicies]);

  const onTabSelect = (_, tabIndex) => {
    navigate(`#${tabIndex}`);
  };

  return {activeTab, onTabSelect};
};
