# coding: utf-8
from __future__ import absolute_import

from typing import List

from ibutsu_server import util
from ibutsu_server.models.artifact import Artifact
from ibutsu_server.models.base_model_ import Model
from ibutsu_server.models.pagination import Pagination


class ArtifactList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, artifacts=None, pagination=None):  # noqa: E501
        """ArtifactList - a model defined in OpenAPI

        :param artifacts: The artifacts of this ArtifactList.  # noqa: E501
        :type artifacts: List[Artifact]
        :param pagination: The pagination of this ArtifactList.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {"artifacts": List[Artifact], "pagination": Pagination}

        self.attribute_map = {"artifacts": "artifacts", "pagination": "pagination"}

        self._artifacts = artifacts
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> "ArtifactList":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ArtifactList of this ArtifactList.  # noqa: E501
        :rtype: ArtifactList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def artifacts(self):
        """Gets the artifacts of this ArtifactList.


        :return: The artifacts of this ArtifactList.
        :rtype: List[Artifact]
        """
        return self._artifacts

    @artifacts.setter
    def artifacts(self, artifacts):
        """Sets the artifacts of this ArtifactList.


        :param artifacts: The artifacts of this ArtifactList.
        :type artifacts: List[Artifact]
        """

        self._artifacts = artifacts

    @property
    def pagination(self):
        """Gets the pagination of this ArtifactList.


        :return: The pagination of this ArtifactList.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this ArtifactList.


        :param pagination: The pagination of this ArtifactList.
        :type pagination: Pagination
        """

        self._pagination = pagination
