# coding: utf-8
from __future__ import absolute_import

from typing import List

from ibutsu_server import util
from ibutsu_server.models.base_model_ import Model
from ibutsu_server.models.group import Group
from ibutsu_server.models.pagination import Pagination


class GroupList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, groups=None, pagination=None):  # noqa: E501
        """GroupList - a model defined in OpenAPI

        :param groups: The groups of this GroupList.  # noqa: E501
        :type groups: List[Group]
        :param pagination: The pagination of this GroupList.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {"groups": List[Group], "pagination": Pagination}

        self.attribute_map = {"groups": "groups", "pagination": "pagination"}

        self._groups = groups
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> "GroupList":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GroupList of this GroupList.  # noqa: E501
        :rtype: GroupList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def groups(self):
        """Gets the groups of this GroupList.


        :return: The groups of this GroupList.
        :rtype: List[Group]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this GroupList.


        :param groups: The groups of this GroupList.
        :type groups: List[Group]
        """

        self._groups = groups

    @property
    def pagination(self):
        """Gets the pagination of this GroupList.


        :return: The pagination of this GroupList.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this GroupList.


        :param pagination: The pagination of this GroupList.
        :type pagination: Pagination
        """

        self._pagination = pagination
