# coding: utf-8
from __future__ import absolute_import

from ibutsu_server import util
from ibutsu_server.models.base_model_ import Model


class Group(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None):
        """Group - a model defined in OpenAPI

        :param id: The id of this Group.
        :type id: str
        :param name: The name of this Group.
        :type name: str
        """
        self.openapi_types = {"id": str, "name": str}

        self.attribute_map = {"id": "id", "name": "name"}

        self._id = id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> "Group":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Group of this Group.
        :rtype: Group
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Group.

        Unique ID of the project

        :return: The id of this Group.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Group.

        Unique ID of the project

        :param id: The id of this Group.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Group.

        The name of the group

        :return: The name of this Group.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Group.

        The name of the group

        :param name: The name of this Group.
        :type name: str
        """

        self._name = name
