# coding: utf-8
from __future__ import absolute_import

from ibutsu_server import util
from ibutsu_server.models.base_model_ import Model


class Health(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, message=None):  # noqa: E501
        """Health - a model defined in OpenAPI

        :param status: The status of this Health.  # noqa: E501
        :type status: str
        :param message: The message of this Health.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {"status": str, "message": str}

        self.attribute_map = {"status": "status", "message": "message"}

        self._status = status
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> "Health":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Health of this Health.  # noqa: E501
        :rtype: Health
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this Health.

        The status of the database, one of \"OK\", \"Error\", \"Pending\"  # noqa: E501

        :return: The status of this Health.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Health.

        The status of the database, one of \"OK\", \"Error\", \"Pending\"  # noqa: E501

        :param status: The status of this Health.
        :type status: str
        """

        self._status = status

    @property
    def message(self):
        """Gets the message of this Health.

        A message to explain the current status  # noqa: E501

        :return: The message of this Health.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Health.

        A message to explain the current status  # noqa: E501

        :param message: The message of this Health.
        :type message: str
        """

        self._message = message
