# coding: utf-8
from __future__ import absolute_import

from ibutsu_server import util
from ibutsu_server.models.base_model_ import Model


class HealthRating(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, health=None):
        """HealthRating - a model defined in Swagger

        :param health: The health of this HealthRating.
        :type health: object
        """
        self.openapi_types = {"health": object}

        self.attribute_map = {
            "id": "id",
            "test_id": "test_id",
            "starttime": "starttime",
            "duration": "duration",
            "result": "result",
            "health": "health",
            "params": "params",
            "source": "source",
        }

        self._health = health

    @classmethod
    def from_dict(cls, dikt) -> "HealthRating":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthRating of this HealthRating.
        :rtype: HealthRating
        """
        return util.deserialize_model(dikt, cls)

    @property
    def health(self):
        """Gets the health of this HealthRating.


        :return: The health of this HealthRating.
        :rtype: object
        """
        return self._health

    @health.setter
    def health(self, health):
        """Sets the health of this HealthRating.


        :param health: The health of this HealthRating.
        :type health: object
        """

        self._health = health
