# coding: utf-8
from __future__ import absolute_import

from typing import List

from ibutsu_server import util
from ibutsu_server.models.base_model_ import Model
from ibutsu_server.models.pagination import Pagination
from ibutsu_server.models.report import Report


class ReportList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reports=None, pagination=None):  # noqa: E501
        """ReportList - a model defined in OpenAPI

        :param reports: The reports of this ReportList.  # noqa: E501
        :type reports: List[Report]
        :param pagination: The pagination of this ReportList.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {"reports": List[Report], "pagination": Pagination}

        self.attribute_map = {"reports": "reports", "pagination": "pagination"}

        self._reports = reports
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> "ReportList":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReportList of this ReportList.  # noqa: E501
        :rtype: ReportList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reports(self):
        """Gets the reports of this ReportList.


        :return: The reports of this ReportList.
        :rtype: List[Report]
        """
        return self._reports

    @reports.setter
    def reports(self, reports):
        """Sets the reports of this ReportList.


        :param reports: The reports of this ReportList.
        :type reports: List[Report]
        """

        self._reports = reports

    @property
    def pagination(self):
        """Gets the pagination of this ReportList.


        :return: The pagination of this ReportList.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this ReportList.


        :param pagination: The pagination of this ReportList.
        :type pagination: Pagination
        """

        self._pagination = pagination
