# coding: utf-8
from __future__ import absolute_import

from ibutsu_server import util
from ibutsu_server.models.base_model_ import Model


class Run(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, duration=None, summary=None, metadata=None):
        """test run - a model defined in Swagger

        :param id: The id of this test run.
        :type id: str
        :param duration: The duration of this test run.
        :type duration: float
        :param summary: The summary of this test run.
        :type summary: Dict[str, str]
        :param metadata: Extra metadata
        :type metadata: Dict[str, str]
        """
        self.openapi_types = {"id": str, "duration": float, "summary": object, "metadata": object}

        self.attribute_map = {
            "id": "id",
            "duration": "duration",
            "summary": "summary",
            "metadata": "metadata",
        }

        self._id = id
        self._duration = duration
        self._summary = summary
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> "Run":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The test run of this test run.
        :rtype: Run
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Run.

        Unique id

        :return: The id of this Run.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Run.

        Unique id

        :param id: The id of this Run.
        :type id: str
        """

        self._id = id

    @property
    def duration(self):
        """Gets the duration of this test run.

        Duration of test in seconds.

        :return: The duration of this test run.
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this test run.

        Duration of test in seconds.

        :param duration: The duration of this test run.
        :type duration: float
        """

        self._duration = duration

    @property
    def summary(self):
        """Gets the summary of this test run.


        :return: The summary of this test run.
        :rtype: object
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this test run.


        :param summary: The summary of this test run.
        :type summary: object
        """

        self._summary = summary

    @property
    def metadata(self):
        """Gets the metadata of this test run.


        :return: The metadata of this test run.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this test run.


        :param metadata: The metadata of this test run.
        :type metadata: object
        """

        self._metadata = metadata
