# coding: utf-8
from __future__ import absolute_import

from typing import List

from ibutsu_server import util
from ibutsu_server.models.base_model_ import Model
from ibutsu_server.models.pagination import Pagination
from ibutsu_server.models.run import Run


class RunList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, runs=None, pagination=None):  # noqa: E501
        """RunList - a model defined in OpenAPI

        :param runs: The runs of this RunList.  # noqa: E501
        :type runs: List[Run]
        :param pagination: The pagination of this RunList.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {"runs": List[Run], "pagination": Pagination}

        self.attribute_map = {"runs": "runs", "pagination": "pagination"}

        self._runs = runs
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> "RunList":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunList of this RunList.  # noqa: E501
        :rtype: RunList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def runs(self):
        """Gets the runs of this RunList.


        :return: The runs of this RunList.
        :rtype: List[Run]
        """
        return self._runs

    @runs.setter
    def runs(self, runs):
        """Sets the runs of this RunList.


        :param runs: The runs of this RunList.
        :type runs: List[Run]
        """

        self._runs = runs

    @property
    def pagination(self):
        """Gets the pagination of this RunList.


        :return: The pagination of this RunList.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this RunList.


        :param pagination: The pagination of this RunList.
        :type pagination: Pagination
        """

        self._pagination = pagination
