FROM registry.access.redhat.com/ubi9/python-39:9.6

ENV UPGRADE_PIP_TO_LATEST=1

USER 0
RUN dnf install -y jq-1.6 && \
    dnf clean all && \
    pip install -U --no-cache-dir schemathesis~=3.29

USER 1001
WORKDIR ${APP_ROOT}/src
COPY docker/start_fuzz_testing.sh .

CMD ["./start_fuzz_testing.sh"]
