FROM registry.access.redhat.com/ubi8/python-38

# add application sources with correct perms for OCP
USER 0
COPY . /app
WORKDIR /app
RUN chown -R 1001:0 ./
USER 1001

# Install deps
RUN pip install --no-cache-dir -U pip && pip install --no-cache-dir -r requirements.txt
# Run application
CMD ["python", "/app/ibutsu_server/tasks/monitor.py"]
