# Template for ibutsu flower monitoring
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ibutsu-flower-template
# ===============================================
# Flower
# ===============================================
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    labels:
      app: ibutsu-flower
    name: ibutsu-flower
    namespace: ${NAMESPACE}
    annotations:
      image.openshift.io/triggers: >-
        [{"from":{"kind":"ImageStreamTag","name":"flower:latest","namespace":"${NAMESPACE}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ibutsu-flower\")].image","pause":"true"}]
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ibutsu-flower
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ibutsu-flower
      spec:
        containers:
        - env:
          - name: CELERY_BROKER_URL
            value: redis://:${REDIS_PASSWORD}@redis.${NAMESPACE}.svc:6379
          - name: CELERY_RESULT_BACKEND
            value: redis://:${REDIS_PASSWORD}@redis.${NAMESPACE}.svc:6379
          image: flower
          imagePullPolicy: Always
          name: ibutsu-flower
          ports:
          - containerPort: 5555
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ibutsu-flower
        from:
          kind: ImageStreamTag
          name: flower:latest
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange
# -----------------------------------------------
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: flower
    annotations:
      description: "Flower monitoring application for Celery task queues"
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: quay.io/ibutsu/flower:latest
      importPolicy:
        scheduled: true
      name: latest
# -----------------------------------------------
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: ibutsu-flower
    namespace: ${NAMESPACE}
  spec:
    ports:
    - port: 8080
      targetPort: 5555
      name: web
    selector:
      app: ibutsu-flower
# -----------------------------------------------
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: ibutsu-flower
    namespace: ${NAMESPACE}
    annotations:
      description: "Route to Celery Flower monitoring interface"
  spec:
    host: ${FLOWER_ROUTE}
    port:
      targetPort: web
    to:
      kind: Service
      name: ibutsu-flower
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
# ===============================================
# Parameters
# ===============================================
parameters:
- name: APP_NAME
  displayName: App Name
  description: The name of the application
  value: ibutsu-server
- name: NAMESPACE
  displayName: Namespace
  description: The namespace for all of the images, applications, etc.
  value: iqe-ibutsu-server
- name: FLOWER_ROUTE
  displayName: Flower Route
  description: The URL for the Flower monitoring interface
  value: ibutsu-flower.example.com
- name: REDIS_PASSWORD
  displayName: Redis Password
  description: The password for Redis
  generate: expression
  from: '[\w]{16}'
